# Generated by Django 5.2.4 on 2025-08-26 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='table_of_content',
            field=models.TextField(blank=True, null=True, verbose_name='Table Of Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 26, 16, 11, 5, 744767, tzinfo=datetime.timezone.utc), verbose_name='Updated At'),
        ),
    ]
