# Generated by Django 5.2.4 on 2025-09-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='posttag',
            unique_together={('post', 'tag')},
        ),
    ]
