# Generated by Django 6.0 on 2026-01-05 17:48

import apps.posts.helper_func
import apps.posts.validators
import datetime
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_posttag_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posttag',
            options={'ordering': ['created_at'], 'verbose_name': 'Post Tag', 'verbose_name_plural': 'Post Tags'},
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='posttag',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='post',
            name='read_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='Read Time'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.posts.helper_func.get_post_thumbnail_path, validators=[apps.posts.validators.post_thumbnail_validator, django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='Post Thumbnail'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.posts.helper_func.get_post_image_path, validators=[apps.posts.validators.post_image_validator, django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='Post Image'),
        ),
        migrations.AddConstraint(
            model_name='postlike',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_post_like'),
        ),
        migrations.AddConstraint(
            model_name='posttag',
            constraint=models.UniqueConstraint(fields=('post', 'tag'), name='unique_post_tag'),
        ),
    ]
