# Generated by Django 5.2.4 on 2025-07-28 14:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('subject', models.CharField(max_length=400, verbose_name='Subject')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Is Reviewed?')),
                ('action', models.CharField(blank=True, max_length=200, null=True, verbose_name='Action')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_comments', to=settings.AUTH_USER_MODEL, verbose_name='Reported By')),
                ('reported_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reports', to='comments.comment', verbose_name='Reported Comment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_comment_reports', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
            options={
                'verbose_name': 'Comment Report',
                'verbose_name_plural': 'Comment Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('subject', models.CharField(max_length=400, verbose_name='Subject')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Is Reviewed?')),
                ('action', models.CharField(blank=True, max_length=200, null=True, verbose_name='Action')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_posts', to=settings.AUTH_USER_MODEL, verbose_name='Reported By')),
                ('reported_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reports', to='posts.post', verbose_name='Reported Post')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_post_reports', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
            options={
                'verbose_name': 'Post Report',
                'verbose_name_plural': 'Post Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('subject', models.CharField(max_length=400, verbose_name='Subject')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Is Reviewed?')),
                ('action', models.CharField(blank=True, max_length=200, null=True, verbose_name='Action')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_users', to=settings.AUTH_USER_MODEL, verbose_name='Reported By')),
                ('reported_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports', to=settings.AUTH_USER_MODEL, verbose_name='Reported To')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_user_reports', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
            options={
                'verbose_name': 'User Report',
                'verbose_name_plural': 'User Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
