# Generated by Django 6.0 on 2026-01-21 19:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_commentlike_unique_together_and_more'),
        ('posts', '0005_alter_posttag_options_alter_postlike_unique_together_and_more'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='commentreport',
            constraint=models.UniqueConstraint(fields=('reported_by', 'reported_comment'), name='unique_user_comment_report'),
        ),
        migrations.AddConstraint(
            model_name='postreport',
            constraint=models.UniqueConstraint(fields=('reported_by', 'reported_post'), name='unique_user_post_report'),
        ),
        migrations.AddConstraint(
            model_name='userreport',
            constraint=models.UniqueConstraint(fields=('reported_by', 'reported_to'), name='unique_user_user_report'),
        ),
    ]
