# Generated by Django 5.2.4 on 2025-07-28 14:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('title', models.CharField(error_messages={'max_length': 'Too long. Max - 300'}, max_length=300, verbose_name='Title')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_lists', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Post List',
                'verbose_name_plural': 'Post Lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='posts.post', verbose_name='Post')),
                ('post_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_list_items', to='post_lists.postlist', verbose_name='Post List')),
            ],
            options={
                'verbose_name': 'Post List Item',
                'verbose_name_plural': 'Post List Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostListLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('post_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_likes', to='post_lists.postlist', verbose_name='Post List')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_lists', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Post List Like',
                'verbose_name_plural': 'Post List Likes',
                'ordering': ['-created_at'],
            },
        ),
    ]
