# Generated by Django 6.0 on 2026-01-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlist',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated At'),
        ),
    ]
