# Generated by Django 5.2.4 on 2025-07-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Bio'),
        ),
    ]
