# Generated by Django 6.0 on 2026-01-05 17:48

import apps.accounts.helper_func
import apps.accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_bio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollow',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.helper_func.get_profile_image_path, validators=[apps.accounts.validators.profile_image_validator, django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='Profile Image'),
        ),
        migrations.AddConstraint(
            model_name='userfollow',
            constraint=models.UniqueConstraint(fields=('follower', 'following'), name='unique_user_follow'),
        ),
    ]
